FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /app
COPY . .
RUN mvn clean install -DskipTests
RUN ls -l /app/target  # Kiểm tra xem có file JAR nào được tạo ra hay không

# Chạy ứng dụng Spring Boot
CMD ["java", "-jar", "target/backend-1.0-SNAPSHOT.jar"]
